# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FaceIdentificationService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'FaceIdentificationService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x46\x61\x63\x65IdentificationService.proto\x12\x0cjsk.services\"G\n\x19\x46\x61\x63\x65IdentificationRequest\x12\r\n\x05Image\x18\x01 \x01(\x0c\x12\x1b\n\x13\x43onfidenceThreshold\x18\x02 \x01(\x02\"~\n\x0eIdentifiedFace\x12\x12\n\nConfidence\x18\x01 \x01(\x02\x12\x0f\n\x07\x43\x65nterX\x18\x02 \x01(\x05\x12\x0f\n\x07\x43\x65nterY\x18\x03 \x01(\x05\x12\x10\n\x08\x42oxWidth\x18\x04 \x01(\x05\x12\x11\n\tBoxHeight\x18\x05 \x01(\x05\x12\x11\n\tEmbedding\x18\x06 \x03(\x02\"I\n\x1a\x46\x61\x63\x65IdentificationResponse\x12+\n\x05\x46\x61\x63\x65s\x18\x01 \x03(\x0b\x32\x1c.jsk.services.IdentifiedFace2z\n\x19\x46\x61\x63\x65IdentificationService\x12]\n\x08Identify\x12\'.jsk.services.FaceIdentificationRequest\x1a(.jsk.services.FaceIdentificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FaceIdentificationService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FACEIDENTIFICATIONREQUEST']._serialized_start=49
  _globals['_FACEIDENTIFICATIONREQUEST']._serialized_end=120
  _globals['_IDENTIFIEDFACE']._serialized_start=122
  _globals['_IDENTIFIEDFACE']._serialized_end=248
  _globals['_FACEIDENTIFICATIONRESPONSE']._serialized_start=250
  _globals['_FACEIDENTIFICATIONRESPONSE']._serialized_end=323
  _globals['_FACEIDENTIFICATIONSERVICE']._serialized_start=325
  _globals['_FACEIDENTIFICATIONSERVICE']._serialized_end=447
# @@protoc_insertion_point(module_scope)
